# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anthony Tan
title: DevOps Engineer | STARLAB
email: tan_537@hotmail.com
website: waahhaa.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: waahhaa
github_username:  waahhaa
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: waahhaa
# flickr_username: jekyll
instagram_username: waahhaa
linkedin_username: anthonytyt
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: waahhaa
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello everyone, Anthony here! I am a passionate individual with a relentless drive for optimizing software development and deployment processes. My journey in the world of technology has been nothing short of an exciting adventure, and I take pride in my ability to bridge the gap between development and operations, making software delivery more efficient, reliable, and scalable. With a background in software development, I have cultivated a good understanding of the software development lifecycle. My expertise lies in designing and implementing CI/CD pipelines, container orchestration, infrastructure as code, and cloud computing. Regularly, I conduct coaching and training for fellow engineers who wishes to learn more about the field of DevOps.

content:
  - title: Technical Achievements # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Deployment of Kubernetes at Scale for Production Environment
        link: github.com/STARLAB
        # link_text: Project Website
        additional_links:
          - title:  github.com/STARLAB
            icon: fab fa-github
            url: https://github.com/STARLAB1733/starlab-ansible-okd
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          1) Automate deployment of Red Hat Openshift Kubernetes Distribution (OKD) Cluster on Production Environment 
          2) Automate deployment of app containers via Helm Charts, resulted to huge deployment time savings and less human error.

        description: | # this will include new lines to allow paragraphs
          OpenShift is a powerful container orchestration platform that enables organizations to manage and deploy containerized applications efficiently. Achieving this in a production environment involves several complex tasks and bring about several benefits, including scalability, reliability, and automation to my organization.

          Key technical areas:

          - Infrastructure as Code (IaC): Implementing IaC principles using tools like Ansible to automate the provisioning and configuration of the underlying infrastructure. This ensures consistency, repeatability, and scalability.
          - High Availability (HA) Setup: Designing an HA architecture for the OpenShift cluster to ensure that it can withstand hardware or software failures. This involves setting up multiple master and worker nodes, load balancing, and distributed storage solutions.
          - Security Hardening: Implementing rigorous security practices to protect the cluster from threats and vulnerabilities. This includes setting up Role-Based Access Control (RBAC), network policies, and integrating with identity and access management systems.
          - Network Configuration: Configuring the networking components of the cluster, including overlay networks, service meshes, and Ingress controllers, to ensure that applications can communicate efficiently and securely.
          - Continuous Integration and Continuous Deployment (CI/CD): Integrating OpenShift with CI/CD pipelines to automate the deployment of containerized applications. This allows for rapid and reliable application releases.
          - Monitoring and Logging: Implementing monitoring and logging solutions like Prometheus and Grafana to gain visibility into the cluster's health and application performance. Setting up alerting mechanisms to detect and respond to issues proactively.
          - Disaster Recovery: Automating the setup of OKD cluster to speed up re-installation of cluster, ensures persistent volume are properly provisioned for data integrity and business continuity in case of catastrophic failures.
          - Rolling Updates and Rollbacks: Implementing strategies for rolling updates and rollbacks of applications to minimize downtime and reduce the impact of potential issues.
          - Scaling and Load Balancing: Implementing auto-scaling for applications and load balancing to handle varying workloads efficiently.
          - Documentation and Knowledge Sharing: Maintaining detailed documentation for the entire OpenShift cluster setup and regularly sharing knowledge with the DevOps team to ensure that everyone is well-informed and can manage the cluster effectively.

      - layout: top-middle
        title: Provisioning DevOps on Openshift using Helm
        link: github.com/STARLAB
        # link_text: Project Website
        additional_links:
          - title:  github.com/STARLAB
            icon: fab fa-github
            url: https://github.com/STARLAB1733/starlab-ansible-okd
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Having this "DevOps from a box solution" offer several significant benefits to my organizations, helping them improve their software development and IT operations processes, enhance collaboration between teams, and deliver better products and services
        description: | # this will include new lines to allow paragraphs
          A complete CI-CD environment DevOps with Cloud Native Pipeline, applying the best practices and using the package manager for Kubernetes, the helm. The ideal is to keep this solution simple so as to easily replicate this DevOps environment across different platforms.

          This DevOps environment includes deployment of:

          - 4 Namespaces, 1 to cicd (infra tools), development, staging and production (app's environments)
          - OpenShift Pipelines (Tekton) for build the app image in each git commit
          - OpenShift GitOps (ArgoCD) for deliver the app in OpenShift cluster
          - Gitea git server for version control and collaborative features
          - Sonatype Nexus for storing build artifacts
          - SonarQube for collection and analysis of source code, and provides reports for the code quality of our project
    
      - layout: top-middle
        title: Building Staging & Development Environment
        link: github.com/STARLAB
        # link_text: Project Website
        additional_links:
          - title:  github.com/STARLAB
            icon: fab fa-github
            url: https://github.com/STARLAB1733/starlab-ansible-okd
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          1) Cost-savings solution to building a new Staging Environment that minimally mirrors the Production Environment
          2) Extension of external agencies's development environment for my developers 

        description: | # this will include new lines to allow paragraphs
          1) The cost savings solution involves the re-purpose of bare-metal servers. Architecting the design and implementation opensource free DevOps Tooling and container orchestrator such as OKD. The staging environment benefits my developers by providing a safe, realistic, and controlled testing environment where they can validate their code, test new features, collaborate with team members, and prevent issues from reaching the production environment. This leads to higher code quality, fewer production issues, and a smoother development process.
          2) Extension of new external agency's development environment allows my developers to be exposed to more developer tools and computing resources. In achieving that, I actively participate and contributed as technical consultant to the project management team and on-site engineers
  
  - title: Skill Set & Certification # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am most skilled in DevOps Environment & Tooling such as: <mark>Kubernetes</mark> , <mark>Docker</mark> , <mark>OpenShift Container Platform</mark> , <mark>Ansible</mark> , <mark>ArgoCD</mark> , <mark>Helm</mark> , <mark>Git/tea</mark> , <mark>SonarQube</mark>
      
      My DevOps Certifications are:
      - GIAC Cloud Security Automation (GCSA)
      - Nutanix Certified Professional - Multi-Cloud Infrastructure (NCP-MCI)
      - Red Hat Openshift Administrator
      - Red Hat System Administration
      - ...

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Singapore Management University
        caption: 2016 - 2020
        sub_title: BSc of Science (Information Systems Management)
        quote: >
          Established in 2000, SMU's mission is to generate leading-edge research with global impact and to produce broad-based, creative, and entrepreneurial leaders for the knowledge-based economy. SMU's education is known for its highly interactive, collaborative, and project-based approach to learning.
        description: | # this will include new lines to allow paragraphs
          During my time at SMU, I learnt most of my core skills that have I have taken through my career such as tech-collaboration and working through tight deadlines. The comprehensive curriculum integrated technology, business management, and information systems. I've gained a deep understanding of how to effectively design, implement, and manage information systems to support organizations' strategic goals. My coursework included subjects like database management, cybersecurity, project management, and data analysis. Additionally, I honed problem-solving and critical thinking skills, and had the opportunity to work on real-world projects that enhanced my practical knowledge.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in DevOps, some of my other interests and hobbies are:
      - Camping
      - Gaming
      - Fish-Keeping
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
